version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4
    restart: always
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - "8081:8080"
